version: '3.9'

services:
  database:
    profiles: ["run", "unittest"]
    restart: always
    image: postgres:15-alpine
    container_name: cn_rest_db
    environment:
      - POSTGRES_DB=rest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thepassword
    ports:
      - 5432:5432

  rest:
    profiles: ["run"]
    build: .
    container_name: cn_rest
    environment:
      - POSTGRES_DATABASE=rest
    command: /app/main
    ports:
      - 3000:3000
    depends_on:
      - database