version: '3.9'

networks:
  connector.ex:
    driver: bridge

services:
  db:
    profiles: ["migrations", "run", "unittest"]
    restart: always
    image: postgres:latest
    container_name: cn_rest_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust 
    volumes:
      - ../.database/postgres/data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - connector.ex

  rest:
    profiles: ["run"]
    build: .
    container_name: cn_rest
    command: /app/main
    ports:
      - 3000:3000
    # depends_on:
    #   - db
    networks:
      - connector.ex

  migrate:
    profiles: ["migrations", "unittest"]
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:thepassword@cn_rest_db:5432/rest?sslmode=disable", "up", "2"]
    links: 
      - db
    networks:
      - connector.ex
