version: '3.9'

networks:
  connector.ex:
    driver: bridge

services:
  db:
    profiles: ["run", "unittest"]
    restart: always
    image: postgres:latest
    container_name: cn_rest_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust 
    volumes:
      - ../.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - connector.ex

  rest:
    profiles: ["run"]
    build: .
    container_name: cn_rest
    environment:
      - POSTGRES_DATABASE=rest
    command: /app/main
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - connector.ex

