version: '3.8'

networks:
  connector.ex:
    driver: bridge

services:
  db:
    restart: always
    image: postgres:latest
    container_name: cn_rest_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thepassword
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../.database/postgres/data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - connector.ex

  rest:
    build: .
    container_name: cn_rest
    command: /app/main
    ports:
      - 8000:8080
    environment:
      - CONFIG_PATH=/bin/config.yaml
      - CONFIG_DRIVER=yaml
      - DB_PASSWORD=thepassword
    depends_on:
      - db
    networks:
      - connector.ex

  migrate:
    image: migrate/migrate
    volumes:
      - .:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:thepassword@cn_rest_db:5432/rest?sslmode=disable", "up", "1"]
    links: 
      - db
    networks:
      - connector.ex
