### CREATE

POST http://localhost:3000/api/v1/article HTTP/1.1
content-type: application/json

{
    "title": "Title 1",
    "url": "htttp://blog.eu/article1"
}

### RETRIEVE Article

GET http://localhost:3000/api/v1/article/1

### RETRIEVE Articles

GET http://localhost:3000/api/v1/article/

### UPDATE

PUT http://localhost:3000/api/v1/article HTTP/1.1
content-type: application/json

{
    "id": 1,
    "title": "Title 1",
    "url": "updated URL"
}

### DELETE

DELETE  http://localhost:3000/api/v1/article/1 HTTP/1.1
