### CREATE Item
POST http://localhost:3000/api/v1/article HTTP/1.1
content-type: application/json

{
    "title": "Title 1",
    "url": "htttp://blog.eu/article1"
}

### RETRIEVE Item
GET http://localhost:3000/api/v1/article/1

### RETRIEVE Items All
GET http://localhost:3000/api/v1/articles/all/

### RETRIEVE Items Paginated
GET http://localhost:3000/api/v1/articles?limit=2&page=1

### UPDATE
PUT http://localhost:3000/api/v1/article/1 HTTP/1.1
content-type: application/json

{
    "url": "updated URL"
}

### DELETE
DELETE  http://localhost:3000/api/v1/article/1 HTTP/1.1

