### CREATE

POST http://localhost:3000/api/v1/article HTTP/1.1
content-type: application/json

{
    "title": "Title 1",
    "url": "htttp://blog.eu/article1"
}

### RETRIEVE Article

GET http://localhost:3000/api/v1/article/6

### RETRIEVE Articles Paginated

GET http://localhost:3000/api/v1/articles/

### RETRIEVE Articles All

GET http://localhost:3000/api/v1/articles/all/

### RETRIEVE Articles Paginated

GET http://localhost:3000/api/v1/articles?limit=10&page=1


### UPDATE

PUT http://localhost:3000/api/v1/article HTTP/1.1
content-type: application/json

{
    "id": 1,
    "url": "updated URL"
}

### UPDATE

PUT http://localhost:3000/api/v1/article/70 HTTP/1.1
content-type: application/json

{
    "url": "updated URL"
}

### DELETE

DELETE  http://localhost:3000/api/v1/article/1 HTTP/1.1

